# 基础镜像
FROM nvidia/cuda:11.8.0-runtime-ubuntu22.04

# 更新系统并安装必要的软件
RUN apt-get update && apt-get install -y \
    wget \
    aria2 \
    cmake \
    build-essential \
    git 

# 安装 Miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda clean -ya
ENV PATH /opt/conda/bin:$PATH

# # 克隆 git 仓库并创建新的 conda 环境
# RUN git clone https://github.com/SizheAn/PanoHead.git /workspace/PanoHead
# WORKDIR /workspace/PanoHead
# RUN conda env create -f environment.yml

# # 添加新环境到 PATH 并安装 JupyterLab
# ENV PATH /opt/conda/envs/panohead/bin:$PATH
RUN pip install jupyterlab

# 设置 Jupyter Notebook 配置文件
RUN ln -s $(which jupyter-lab) /usr/local/bin/jupyter-notebook
RUN jupyter notebook --generate-config
RUN echo "c.ServerApp.token = ''" >> /root/.jupyter/jupyter_lab_config.py
RUN echo "c.ServerApp.password = ''" >> /root/.jupyter/jupyter_lab_config.py
RUN echo "c.ServerApp.open_browser = False" >> /root/.jupyter/jupyter_lab_config.py
RUN echo "c.ServerApp.ip = '0.0.0.0'" >> /root/.jupyter/jupyter_lab_config.py
RUN echo "c.ServerApp.port = 8888" >> /root/.jupyter/jupyter_lab_config.py
RUN echo "c.ServerApp.terminado_settings = {'shell_command': ['/bin/bash']}" >> /root/.jupyter/jupyter_lab_config.py

# 创建工作目录
# RUN mkdir /workspace
WORKDIR /workspace

# 创建 JupyterLab 启动脚本
RUN echo "#!/bin/bash" >> /root/start.sh
RUN echo bash -c "jupyter lab --allow-root" >> /root/start.sh
RUN chmod +x /root/start.sh

# 开放端口
EXPOSE 8888

# 启动命令
CMD ["/bin/bash", "/root/start.sh"]